# Testing

In [1]:
import warnings
warnings.filterwarnings("ignore",category=DeprecationWarning,message='.*') 
warnings.filterwarnings("ignore",category=FutureWarning,message='.*')
warnings.filterwarnings("ignore",category=PendingDeprecationWarning,message='.*')

In [1]:
import numpy as np
import os
import pandas as pd
import open3d as o3d
import tensorflow as tf

import gym
from stable_baselines3 import PPO

from Augmentation import Augmentation
from PcdController import PcdController as cloud
from FootEnvironment import FootEnv

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [63]:
l = Augmentation.load_folder('pc_out')

In [20]:
sizes = [len(i.points) for i in l]

In [24]:
sizes.sort()
print(sizes)

[2188, 2188, 2188, 2188, 2188, 2625, 2625, 2625, 2625, 2625, 2639, 2639, 2639, 2639, 2639, 2854, 2854, 2854, 2854, 2854, 3063, 3063, 3063, 3063, 3063, 3166, 3166, 3166, 3166, 3166, 3424, 3424, 3424, 3424, 3424, 3437, 3437, 3437, 3437, 3437, 3500, 3500, 3500, 3500, 3500, 3694, 3694, 3694, 3694, 3694, 3938, 3938, 3938, 3938, 3938, 3995, 3995, 3995, 3995, 3995, 4124, 4124, 4124, 4124, 4124, 4222, 4222, 4222, 4222, 4222, 4421, 4421, 4421, 4421, 4421, 4566, 4566, 4566, 4566, 4566, 4750, 4750, 4750, 4750, 4750, 4811, 4811, 4811, 4811, 4811, 5137, 5137, 5137, 5137, 5137, 5305, 5305, 5305, 5305, 5305, 5362, 5362, 5362, 5362, 5362, 5499, 5499, 5499, 5499, 5499, 5660, 5660, 5660, 5660, 5660, 6002, 6002, 6002, 6002, 6002, 6186, 6186, 6186, 6186, 6186, 6189, 6189, 6189, 6189, 6189, 6434, 6434, 6434, 6434, 6434, 6792, 6792, 6792, 6792, 6792, 7073, 7073, 7073, 7073, 7073, 7202, 7202, 7202, 7202, 7202, 7506, 7506, 7506, 7506, 7506, 7924, 7924, 7924, 7924, 7924, 7957, 7957, 7957, 7957, 7957, 8402, 840

In [42]:
def move(movement):
    squares = np.square(movement)
    total = 0
    for row in squares:
        total += np.sqrt(sum(row))
    return total

In [51]:
foot = pd.read_csv('PointCloudKubus.csv')
points = []
for i in range(len(foot)):
    points.append([foot["X"][i],foot["Y"][i],foot["Z"][i]])
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points)
o3d.io.write_point_cloud('kubus.ply', pcd)

True

In [62]:
movement = [[0.3,0.01,-0.01] for _ in range(8)]
new_pc = np.add(points,movement)
dist = move(movement)
print(f'Moved pointcloud {dist} units:\n',new_pc)

Moved pointcloud 2.4026651868289934 units:
 [[ 3.000e-01  1.000e-02 -1.000e-02]
 [ 1.030e+01  1.000e-02 -1.000e-02]
 [ 3.000e-01  1.001e+01 -1.000e-02]
 [ 3.000e-01  1.000e-02  9.990e+00]
 [ 1.030e+01  1.001e+01 -1.000e-02]
 [ 1.030e+01  1.000e-02  9.990e+00]
 [ 3.000e-01  1.001e+01  9.990e+00]
 [ 1.030e+01  1.001e+01  9.990e+00]]


In [59]:
class Testing():
    def __init__(self):
        self.a = 1
        self.b = 2
        self.c = 3
        self.func()

    def func(self):
        self.d = self.a + self.c

In [70]:
t = l[0]
len(t.points)

4421