# Testing

In [16]:
import warnings
warnings.filterwarnings("ignore",category=DeprecationWarning,message='.*') 
warnings.filterwarnings("ignore",category=FutureWarning,message='.*')
warnings.filterwarnings("ignore",category=PendingDeprecationWarning,message='.*')

In [47]:
import numpy as np
import os
import pandas as pd
import open3d as o3d
import tensorflow as tf

import gym
from stable_baselines import ppo1
from stable_baselines.common.policies import MlpPolicy

from Augmentation import Augmentation
from PcdController import PcdController as cloud
from FootEnvironment import FootEnv

In [19]:
l = Augmentation.load_folder('pc_out')

In [20]:
sizes = [len(i.points) for i in l]

In [24]:
sizes.sort()
print(sizes)

[2188, 2188, 2188, 2188, 2188, 2625, 2625, 2625, 2625, 2625, 2639, 2639, 2639, 2639, 2639, 2854, 2854, 2854, 2854, 2854, 3063, 3063, 3063, 3063, 3063, 3166, 3166, 3166, 3166, 3166, 3424, 3424, 3424, 3424, 3424, 3437, 3437, 3437, 3437, 3437, 3500, 3500, 3500, 3500, 3500, 3694, 3694, 3694, 3694, 3694, 3938, 3938, 3938, 3938, 3938, 3995, 3995, 3995, 3995, 3995, 4124, 4124, 4124, 4124, 4124, 4222, 4222, 4222, 4222, 4222, 4421, 4421, 4421, 4421, 4421, 4566, 4566, 4566, 4566, 4566, 4750, 4750, 4750, 4750, 4750, 4811, 4811, 4811, 4811, 4811, 5137, 5137, 5137, 5137, 5137, 5305, 5305, 5305, 5305, 5305, 5362, 5362, 5362, 5362, 5362, 5499, 5499, 5499, 5499, 5499, 5660, 5660, 5660, 5660, 5660, 6002, 6002, 6002, 6002, 6002, 6186, 6186, 6186, 6186, 6186, 6189, 6189, 6189, 6189, 6189, 6434, 6434, 6434, 6434, 6434, 6792, 6792, 6792, 6792, 6792, 7073, 7073, 7073, 7073, 7073, 7202, 7202, 7202, 7202, 7202, 7506, 7506, 7506, 7506, 7506, 7924, 7924, 7924, 7924, 7924, 7957, 7957, 7957, 7957, 7957, 8402, 840

In [42]:
def move(movement):
    squares = np.square(movement)
    total = 0
    for row in squares:
        total += np.sqrt(sum(row))
    return total

In [51]:
foot = pd.read_csv('PointCloudKubus.csv')
points = []
for i in range(len(foot)):
    points.append([foot["X"][i],foot["Y"][i],foot["Z"][i]])
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points)
o3d.io.write_point_cloud('kubus.ply', pcd)

True

In [58]:
movement = [[1,0,0] for _ in range(8)]
new_pc = np.add(points,movement)
dist = move(movement)
print(f'Moved pointcloud {dist} units:\n',new_pc)

Moved pointcloud 8.0 units:
 [[ 1  0  0]
 [11  0  0]
 [ 1 10  0]
 [ 1  0 10]
 [11 10  0]
 [11  0 10]
 [ 1 10 10]
 [11 10 10]]


In [59]:
class Testing():
    def __init__(self):
        self.a = 1
        self.b = 2
        self.c = 3
        self.func()

    def func(self):
        self.d = self.a + self.c

In [60]:
t = Testing()